---
  - name: init
    command:      git init
    args:
      chdir:      /etc/ansible

  - name: init
    command:      git add *.cfg hosts playbooks roles
    args:
      chdir:      /etc/ansible

  - name: commit
    command:      git commit -m 'initial'
    args:
      chdir:      /etc/ansible

#Need to copy key for github manually! This not for use! Check name for key in template or change it.
#  - name: key
#    command:      ssh-keygen -t rsa -b 8192
#    args:
#      chdir:      /etc/ansible

#  - name: ssh config
#    template:
#      src:        /etc/ansible/roles/git_ansible/templates/config
#      dest:       /root/.ssh/config
#      mode:       400

#  - name: ssh config
#    template:
#      src:        /etc/ansible/roles/git_ansible/templates/config
#      dest:       /root/.ssh/config

#  - name: github
#    command:      git remote add github git@github.com:IAristov/ansible.git
#    args:
#      chdir:      /etc/ansible

#  - name: github_push
#    command:      git push -u github master
#    args:
#      chdir:      /etc/ansible

