---
  - name: init
    command:      git init
    args:
      chdir:      /etc/ansible

  - name: init
    command:      git add *.cfg hosts playbooks roles
    args:
      chdir:      /etc/ansible

  - name: commit
    command:      git commit -m 'initial'
    args:
      chdir:      /etc/ansible

  - name: github
    command:      git remote add git_rsa git@github.com:IAristov/ansible.git
    args:
      chdir:      /etc/ansible

  - name: github_push
    command:      git push -u origin master
    args:
      chdir:      /etc/ansible
