- name: start_docker
  service: 
    name:       docker
    state:      started
    enabled:    yes

- name: json_file
  template:
    src:        /etc/ansible/roles/docker/templates/daemon.json
    dest:       /etc/docker/daemon.json

- name: docker-py
  pip:
    name:       docker-py
    state:      present

- name: clear
  docker_image:
    name:       hello-world
    state:      absent
